[env]
VERSION = { script = ["cargo pkgid | cut -d# -f2 | cut -d: -f2"] }

# === CLI ===
[tasks.build-cli-linux]
script = ["cd core && cargo build --target x86_64-unknown-linux-gnu --release"]

[tasks.build-cli-windows]
script = ["cd core && cargo build --target x86_64-pc-windows-gnu --release"]

[tasks.build-cli-macos-intel]
script = ["cd core && cargo build --target x86_64-apple-darwin --release"]

[tasks.build-cli-macos-apple]
script = ["cd core && cargo build --target aarch64-apple-darwin --release"]

# === GUI ===
[tasks.build-gui-linux]
script = ["cd gui && cargo build --target x86_64-unknown-linux-gnu --release"]

[tasks.build-gui-windows]
script = ["cd gui && cargo build --target x86_64-pc-windows-gnu --release"]

[tasks.build-gui-macos-intel]
script = ["cd gui && cargo build --target x86_64-apple-darwin --release"]

[tasks.build-gui-macos-apple]
script = ["cd gui && cargo build --target aarch64-apple-darwin --release"]

# === Convenience targets ===
[tasks.build-cli]
dependencies = ["build-cli-linux", "build-cli-windows"]

[tasks.build-gui]
dependencies = ["build-gui-linux", "build-gui-windows"]
